# .github/workflows/sync.yml
name: Sync Fork

on:
  schedule:
    - cron: '55 7 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.FORK_SYNCHRONIZATION_PERMISSION }}
          owner: Anduin2017 # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
