# .github/workflows/sync.yml
name: Sync Fork

on:
  schedule:
    - cron: '0 8 * * ?' # 每天北京时间0点触发
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.FORK_SYNCHRONIZATION_PERMISSION }}
          owner: Anduin2017 # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
